#!/usr/bin/env python3
"""Module for async comprehension task."""

import asyncio


async_generator = __import__('0-async_generator').async_generator

async def async_comprehension() -> list:
    """Coroutine that collects 10 random numbers using an async comprehension
    over async_generator, then returns the 10 random numbers.

    Returns:
    list: A list of 10 random float numbers generated by async_generator.
    """
    return [i async for i in async_generator()]
